[package]
name = "aide-macros"
version = "0.5.1"
authors = ["tamasfe"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macros for the Aide library"

[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = "1.0.99"
